language: php
php:
- 7.1
- 7.2
- 7.3
- 7.4

before_install:
# turn off XDebug
- phpenv config-rm xdebug.ini || return 0

install:
# Composer
- travis_retry composer install --no-progress --prefer-dist

script:
# Nette/Tester
- composer run-script tester

jobs:
  include:
  - stage: Quality Assurance
    php: 7.4
    script:
    - composer run-script qa

  - stage: Test Coverage
    php: 7.4
    script:
    - composer run-script coverage
    after_script:
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - php coveralls.phar --verbose --config tests/.coveralls.yml

  - stage: Phpstan
    php: 7.4
    script:
    - composer run-script phpstan-install
    - composer run-script phpstan

  allow_failures:
  - stage: Test Coverage
  - stage: Phpstan

after_failure:
# Print *.actual content
- for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
  - $HOME/.composer/cache
